sudo: false
cache:
- pip
language: python
python:
- '3.5'
- '3.6'
env:
- JAPRONTO=0.1.1
install:
- pip install -U setuptools pep8 coverage docutils pygments japronto==$JAPRONTO
script:
- coverage erase
- nosetests --with-coverage --cover-package=japronto_cors
- python setup.py clean build install
after_success:
- pep8 japronto_cors.py
deploy:
  provider: pypi
  user: gsakkis
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: gsakkis/japronto-cors
  password:
    secure: TODO
